ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" RENAME VALUE 'MEMBER' TO 'USER';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "canManageUsers" BOOLEAN NOT NULL DEFAULT false;

UPDATE "User"
SET "role" = 'SUPER_ADMIN'
WHERE "role" = 'ADMIN';

UPDATE "User"
SET "canManageUsers" = true
WHERE "role" = 'SUPER_ADMIN';
